# 基础镜像
FROM nginx
# author
MAINTAINER zhangcheng

# 挂载目录
VOLUME /home/ruoyi/projects/codeonline-frontend
# 创建目录
RUN mkdir -p /home/ruoyi/projects/codeonline-frontend
# 指定路径
WORKDIR /home/ruoyi/projects/codeonline-frontend
# 复制conf文件到路径
COPY ./nginx/conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./dist /home/ruoyi/projects/codeonline-frontend
